### ISSUE TITLE
namespace regex too greedy

### ISSUE THREAD

**Issue by char101** [phug-php/component#3]
The regex in https://github.com/phug-php/component/blob/master/src/Phug/Component/ComponentExtension.php#L156, when used to match this output
```php
<?php namespace pug; ?><?php $pugModule = [
  'Phug\\Formatter\\Format\\BasicFormat::dependencies_storage' => 'pugModule',
  'Phug\\Formatter\\Format\\BasicFormat::helper_prefix' => 'Phug\\Formatter\\Format\\BasicFormat::',
  'Phug\\Formatter\\Format\\BasicFormat::get_helper' => function ($name) use (&$pugModule) {
```

results in these matches

```
1 => "<?php namespace pug; ?><?php $pugModule = ["
2 => """
  \n
    'Phug\\Formatter\\Format\\BasicFormat::dependencies_storage' => 'pugModule',\n
    'Phug\\Formatter\\Format\\BasicFormat::helper_prefix' => 'Phug\\Formatter\\Format\\BasicFormat::',\n
    'Phug\\Formatter\\Format\\BasicFormat::get_helper' => function ($name) use (&$pugModule) {
```

So `$mixinFunctionsCode` will be inserted inside the array rather than after the namespace.

I propose this simpler regex

```php
if (preg_match('/^<\?php\s*namespace\s+\w+\s*;\s*/', $output, $matches)) {
    return $matches[0].$mixinFunctionsCode.substr($output, strlen($matches[0]));
}
```

**Comment by char101** [comment]
It can be fixed by adding `\n` after the namespace definition but I think it is better to handle both case.

**Comment by kylekatarnls** [comment]
How do you get the output you mention? And how do you define your namespace? Please provide the steps to reproduce your issue.

I tried with many different codes and options and can't get problem with this library using namespace in template.

**Comment by char101** [comment]
I am using the `on_output` option on pug to namespace the templates
```
'on_output' => function ($event) {
    $event->setOutput("<?php namespace pug; ?>".$event->getOutput());
},
```

I also set `php_token_handlers` if it matters
```php
'php_token_handlers' => [T_VARIABLE => null],
```

**Comment by kylekatarnls** [comment]
It's now properly handled in 1.1.4.

Note that last version of phug/phug also provide a standard way to add code at the beginning (but after namespace if present) and can be used for the namespace itself:

```php
'on_output' => function ($event) {
    $event->prependCode('namespace pug;');
},
```

**Comment by char101** [comment]
Thanks, didn't know about the `prependCode` method.

**Comment by kylekatarnls** [comment]
It's brand new :D

I added it because the same logic of namespace detection + prepending code was used in both phug/component and js-phpize/js-phpize-phug so I moved the RegExp inside phug/compiler to be used on need by plugins and user options.
